// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.'
// Run `yarn routely` to regenerate this file.

import { Router } from "routely";

type Routes = [
  {
    pathname: "/foo/[foo]";
    query: { foo: string };
  }
];

export const router = new Router<Routes>([
  {
    pathname: "/foo/[foo]",
    loader: () => import("./routes/foo/[foo]"),
  },
]);
