import { Route } from "./utils";

function getQueryInterface(query: Route["query"]): string {
  let res = "";
  Object.entries(query).forEach(([key, value]) => {
    res += key;
    switch (value) {
      case "dynamic": {
        res += ": string";
        break;
      }
      case "catch-all":
      case "optional-catch-all": {
        res += ": string[]";
        break;
      }
      // istanbul ignore next: unreachable
      case "static": {
        break;
      }
      // istanbul ignore next: unreachable
      default: {
        const _exhaust: never = value;
        return _exhaust;
      }
    }
    res += "; ";
  });

  if (res) {
    return `{ ${res}}`;
  }
  return "never";
}
/*
 
  match<Ctx = Record<string, unknown>(path: keyof manifest, ctx: Ctx): manifest[keyof manifest] {
    for (let route of router.routes) {
      re = route.match(path); 
      if (re.match) {
        return manifest[route.pathname]({
          context: {},
          params: re.params ,
          url: Url
        });
      }
    }
  }

  export const router = new Router<([
    ,
    ,
    ,
  ]);
};
*/

function printIf(cond: boolean, str: string): string {
  return cond ? str : "";
}

export async function generate(routes: Route[]): Promise<string> {
  const isTS = routes.some((route) => route.filepath.includes(".ts"));

  let generated = `\
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.'
// Run \`yarn routely\` to regenerate this file.

import { Router } from "routely";

${printIf(
  isTS,
  `type Routes = [
${routes
  .map(
    (route) =>
      `  {
     pathname: "${route.pathname}";
     query: ${getQueryInterface(route.query)}
  }`
  )
  .join(",\n")}
]`
)}

export const router = new Router${printIf(isTS, `<Routes>`)}([
${routes
  .map(
    (route) =>
      `  {
    pathname: "${route.pathname}",
    loader: () => import("./${route.filepath}")
  }`
  )
  .join(",\n")}
]);
`;

  try {
    const prettier = await import("prettier");
    generated = prettier.format(generated, {
      parser: isTS ? "typescript" : "babel",
    });
  } catch (e) {
    // istanbul ignore next
    console.warn(e);
  }

  return generated;
}
