import { generate } from "./codegen";
import { filepaths } from "./test-utils";
import { getRoutes } from "./utils";

describe("generate", () => {
  it("writes routes", async () => {
    const routes = getRoutes(filepaths);
    expect(await generate(routes)).toMatchInlineSnapshot(`
      "// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.'
      // Run \`yarn routely\` to regenerate this file.

      import { router } from \\"routely\\";

      export type Route =
        | {
            pathname: \\"/\\";
            query: never;
          }
        | {
            pathname: \\"/404\\";
            query: never;
          }
        | {
            pathname: \\"/_app\\";
            query: never;
          }
        | {
            pathname: \\"/_debug\\";
            query: never;
          }
        | {
            pathname: \\"/_document\\";
            query: never;
          }
        | {
            pathname: \\"/_error\\";
            query: never;
          }
        | {
            pathname: \\"/_error/\\";
            query: never;
          }
        | {
            pathname: \\"/not-found\\";
            query: never;
          }
        | {
            pathname: \\"/settings/\\";
            query: never;
          }
        | {
            pathname: \\"/_debug/health-check\\";
            query: never;
          }
        | {
            pathname: \\"/api/bar\\";
            query: never;
          }
        | {
            pathname: \\"/settings/foo\\";
            query: never;
          }
        | {
            pathname: \\"/settings/bars/[bar]\\";
            query: { bar: string };
          }
        | {
            pathname: \\"/settings/bars/[bar]/baz\\";
            query: { bar: string };
          }
        | {
            pathname: \\"/foo/[slug]\\";
            query: { slug: string };
          }
        | {
            pathname: \\"/api/[...segments]\\";
            query: { segments: string[] };
          }
        | {
            pathname: \\"/api/[[...segments]]\\";
            query: { segments: string[] };
          }
        | {
            pathname: \\"/[foo]\\";
            query: { foo: string };
          }
        | {
            pathname: \\"/[foo]/baz\\";
            query: { foo: string };
          }
        | {
            pathname: \\"/[foo]/bar/[baz]\\";
            query: { foo: string; baz: string };
          }
        | {
            pathname: \\"/[foo]/bar/[baz]/foo/[bar]\\";
            query: { foo: string; baz: string; bar: string };
          }
        | {
            pathname: \\"/[foo]/[bar]/[baz]\\";
            query: { foo: string; bar: string; baz: string };
          };

      const manifest = {
        \\"/index.ts\\": () => import(\\".//index.ts\\"),
        \\"/404.ts\\": () => import(\\".//404.ts\\"),
        \\"/_app.ts\\": () => import(\\".//_app.ts\\"),
        \\"/_debug.ts\\": () => import(\\".//_debug.ts\\"),
        \\"/_document.ts\\": () => import(\\".//_document.ts\\"),
        \\"/_error.ts\\": () => import(\\".//_error.ts\\"),
        \\"/_error/index.ts\\": () => import(\\".//_error/index.ts\\"),
        \\"/not-found.ts\\": () => import(\\".//not-found.ts\\"),
        \\"/settings/index.ts\\": () => import(\\".//settings/index.ts\\"),
        \\"/_debug/health-check.ts\\": () => import(\\".//_debug/health-check.ts\\"),
        \\"/api/bar.ts\\": () => import(\\".//api/bar.ts\\"),
        \\"/settings/foo.ts\\": () => import(\\".//settings/foo.ts\\"),
        \\"/settings/bars/[bar].ts\\": () => import(\\".//settings/bars/[bar].ts\\"),
        \\"/settings/bars/[bar]/baz.ts\\": () => import(\\".//settings/bars/[bar]/baz.ts\\"),
        \\"/foo/[slug].ts\\": () => import(\\".//foo/[slug].ts\\"),
        \\"/api/[...segments].ts\\": () => import(\\".//api/[...segments].ts\\"),
        \\"/api/[[...segments]].ts\\": () => import(\\".//api/[[...segments]].ts\\"),
        \\"/[foo].ts\\": () => import(\\".//[foo].ts\\"),
        \\"/[foo]/baz.ts\\": () => import(\\".//[foo]/baz.ts\\"),
        \\"/[foo]/bar/[baz].ts\\": () => import(\\".//[foo]/bar/[baz].ts\\"),
        \\"/[foo]/bar/[baz]/foo/[bar].ts\\": () =>
          import(\\".//[foo]/bar/[baz]/foo/[bar].ts\\"),
        \\"/[foo]/[bar]/[baz].ts\\": () => import(\\".//[foo]/[bar]/[baz].ts\\"),
      };

      export const r = router<Route, typeof manifest>(manifest);
      "
    `);
  });
});
