// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.'
// Run `yarn routely` to regenerate this file.

import { router } from "routely";

export type Route = {
  pathname: "routes/foo/[foo]";
  query: { foo: string };
};

const manifest = {
  "routes/foo/[foo].ts": () => import("./routes/foo/[foo].ts"),
};

export const r = router<Route, typeof manifest>(manifest);
